version: "3"

services:
  kallabox-tui:
    image: ghcr.io/kallabox/kallabox-tui:${KALLABOX_VERSION:-latest}
    restart: always
    networks:
      - kallabox-network
    environment:
      KALLABOX_BASE_URL: ${KALLABOX_BASE_URL:-http://kallabox-api:8888/api}
      KALLABOX_SERVICE_TOKEN: ${KALLABOX_SERVICE_TOKEN:-kallabox_service_token}

networks:
  kallabox-network:
    external: true
